default:
	pipenv run python $(LIBDIR)/batch_http.py upload_eq_collection_instrument.json --host ${COLLECTION_INSTRUMENT_HOST} --port ${COLLECTION_INSTRUMENT_PORT} --username ${COLLECTION_INSTRUMENT_USERNAME} --password ${COLLECTION_INSTRUMENT_PASSWORD} 
