default:
	pipenv run python ../lib/load.py config/${COLLEX_LOAD_CONFIG} \
		--posturl=http://${COLLEX_HOST}:${COLLEX_PORT}/collectionexercises \
		--user=${COLLEX_USER} --password ${COLLEX_PASSWORD}

