default:
	pipenv run python $(LIBDIR)/batch_http.py create_classifiers.json --host ${COMMS_TEMPLATE_HOST} --port ${COMMS_TEMPLATE_PORT} --username ${COMMS_TEMPLATE_USERNAME} --password ${COMMS_TEMPLATE_PASSWORD} 
